### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by kangkang59812** [Maluuba/nlg-eval#73] opened 2019-06-17 08:39 UTC
python3.6

>>>from nlgeval import NLGEval
>>> nlgeval = NLGEval()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lkk/code/caption_v1/nlgeval/nlgeval/__init__.py", line 192, in __init__
    self.load_skipthought_model()
  File "/home/lkk/code/caption_v1/nlgeval/nlgeval/__init__.py", line 226, in load_skipthought_model
    model = skipthoughts.load_model()
  File "/home/lkk/code/caption_v1/nlgeval/nlgeval/skipthoughts/skipthoughts.py", line 59, in load_model
    utable, btable = load_tables()
  File "/home/lkk/code/caption_v1/nlgeval/nlgeval/skipthoughts/skipthoughts.py", line 79, in load_tables
    utable = numpy.load(os.path.join(path_to_tables, 'utable.npy'), allow_pickle=True, encoding='bytes')
  File "/home/lkk/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 433, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/lkk/anaconda3/lib/python3.6/site-packages/numpy/lib/format.py", line 657, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated

**Comment by juharris** [comment] 2019-06-17 13:33
Possible duplicate of https://github.com/Maluuba/nlg-eval/issues/60
Basically it seems like some files may not have finished downloading. You can check #60 for the correct file sizes and which file(s) you can try to delete and re-download. The easiest way to re-download the files is to re-run the setup.

**Comment by juharris** [comment] 2019-06-17 13:33
Possible duplicate of https://github.com/Maluuba/nlg-eval/issues/60
Basically it seems like some files may not have finished downloading. You can check #60 for the correct file sizes and which file(s) you can try to delete and re-download. The easiest way to re-download the files is to re-run the setup.

**Closed** 2019-07-05 13:19 UTC
